### ISSUE TITLE
Regarding last issue: "Doubts regarding the mass concentration(ug/m3) of PM 10 "

### ISSUE THREAD

**Issue by niteshkadyan** [Sensirion/embedded-uart-sps#11]
I am sorry to open an another issue. But, I am still waiting to hear back from sensirion on the [issue](https://github.com/Sensirion/embedded-uart-sps/issues/10) of PM10 being lower than PM2.5 for the sensor I purchased. Kindly direct me to the correct person to talk to, as in few days I have to deploy the sensor in a commercial setting.

**Comment by abrauchli** [comment]
Hi @niteshkadyan, thanks, we got the reply on the closed issue, I also just sent you an email. I'm closing this issues since it's not related to the driver.
