### ISSUE TITLE
"arduino_sps30_example.ino" does not compile

### ISSUE THREAD

**Issue by EKolev** [Sensirion/embedded-uart-sps#13]
I installed embedded-uart-sps following the instructions in the README file.  I am using the arduino implantation from "sample-implementations/Arduino/sensirion_uart_implemenation.cpp" to compile the example arduino sketch and I am getting the following error:

"sensirion_uart_implementation.cpp:51:1: error: 'Uart' does not name a type
 Uart Serial2 (&sercom1, PIN_UART_RX, PIN_UART_TX, SERCOM_RX_PAD_0,
 ^ "

I am using an Arduino Uno board.

I tried the linux version on my Raspberry Pi and it works fine.

**Comment by per1234** [comment]
That code is specific to the SAMD boards like the Zero, MKR, etc. AVR boards like your Uno don't have SERCOM.

**Comment by EKolev** [comment]
I see, I deleted this line and used just 'Serial' in their implementation file and it worked. 

Thank you.

**Comment by abrauchli** [comment]
@per1234, @EKolev thanks for the input, I'll add a comment the file

**Comment by nit1995** [comment]
@EKolev  Can you share the code for Arduino implementation, please?
