### ISSUE TITLE
More generic Arduino sample implementation

### ISSUE THREAD

**Issue by rnestler** [Sensirion/embedded-uart-sps#17]
The [current Arduino sample implementation](https://github.com/Sensirion/embedded-uart-sps/blob/58e314e52e872452b56bb47b6750b95f04d0200e/embedded-uart-common/sample-implementations/arduino/sensirion_uart_implementation.cpp) is very specific to the atsamd21 and uses [private functions](https://github.com/Sensirion/embedded-uart-sps/blob/58e314e52e872452b56bb47b6750b95f04d0200e/embedded-uart-common/sample-implementations/arduino/sensirion_uart_implementation.cpp#L33) to instantiate and configure a new serial port.
It would probably be easier to either support multiple boards with some `#ifdef` magic or just use the always available `Serial` port and add some comments describing how to use other serial ports on different Arduino boards.

**Comment by psachs** [comment]
check out new arduino drivers with more generic examples that work on most arduinos
