### ISSUE TITLE
Distinguish between different SENSIRION_SHDLC_ERR_MISSING_STOP errors

### ISSUE THREAD

**Issue by rnestler** [Sensirion/embedded-uart-sps#25]
We currently return SENSIRION_SHDLC_ERR_MISSING_STOP for three different error cases:
https://github.com/Sensirion/embedded-uart-sps/blob/6e3256e8d4e63dcc49a6e5f322467fabfb8a2400/embedded-uart-common/sensirion_shdlc.c#L180
https://github.com/Sensirion/embedded-uart-sps/blob/6e3256e8d4e63dcc49a6e5f322467fabfb8a2400/embedded-uart-common/sensirion_shdlc.c#L190
https://github.com/Sensirion/embedded-uart-sps/blob/6e3256e8d4e63dcc49a6e5f322467fabfb8a2400/embedded-uart-common/sensirion_shdlc.c#L197
This makes it harder to diagnose errors. We should probably come up with two more error codes to use in these cases.

**Comment by KaninMcGuire** [comment]
![image](https://user-images.githubusercontent.com/56835009/69110499-3ad97e80-0a38-11ea-9fbb-9041b3028991.png)
Here you can use these and create variables to distinguish the errors

**Comment by abrauchli** [comment]
Hi @KaninMcGuire thanks for your input. I think the table you posted is coming from a sensor datasheet like the SPS30 and specify the error codes that are returned from the sensor when the communication protocol is intact - what @rnestler means, is that the SHDLC protocol decoding failed, not the sensor specific commands. You would find that in case of a faulty link (dropped communication, flipped bits, a second device on the bus that doesn't respect SHDLC etc.)

**Comment by abrauchli** [comment]
Fixed with https://github.com/Sensirion/embedded-uart-sps/pull/50 (RFC)

**Comment by rnestler** [comment]
Fixed with #50.
