### ISSUE TITLE
SPS30 communication on uart

### ISSUE THREAD

**Issue by Mohit2183** [Sensirion/embedded-uart-sps#51]
we are facing a critical issue with communication with SPS30 WITH PC
we were testing sps30 by connecting with docklight.
we have used usb to serial converter to command the sps30. 
pin 1 was connected to poer supply +5vdc , 
pin 5 was connected to 0vdc. 
pin4 was left open for UART, 
pin 2 was connected to Tx of master (PC), 
pin 3 was connected to Rx of master (pc). 
From docklight v2.3 we had set the com port , 115200, 8N1 communication settings. 
we have placed command in format of Hex codes i.e. 
start command 
Tx: 7E 00 00 01 02 F9 7E , 
Rx REPLY: 7E 00 00 01 02 F9 7E , 
Tx: 7E 00 00 00 FF 7E, 
Rx REPLY: x: 7E 00 00 00 FF 7E , 
Tx: 7E 00 03 00 FC 7E , 
Rx REPLY: 7E 00 03 00 FC 7E , 
Tx: 7E 00 D3 00 2C 7E, 
Rx REPLY: 7E 00 D3 00 2C 7E . 
OVER ALL FAN IS ALSO NOT ROTATING PHYSICALLY.. 
could you pls guide us why sps30 is not giving response to our commands.
how to proceed further with sps30

**Comment by abrauchli** [comment]
The question does not seem related to the embedded-uart-sps driver in question. Kindly note the post from the closed thread where you posted this question as well:

> There is a support team to provide help with technical questions and issues with Sensirion products. They can be reached via this form: https://www.sensirion.com/en/about-us/contact/. Alternatively, if you bought parts through a distributor, they often have support channels as well.
> 
> For any questions regarding the software, we (the Sensirion github team) are doing our best to provide timely answers, but unfortunately we're too far removed from the commercial and hardware side to go beyond that. Thanks for understanding.
