### ISSUE TITLE
Arduino example wrong #define

### ISSUE THREAD

**Issue by GKassell** [Sensirion/embedded-uart-sps#65]
The Arduino example doesn't compile, as it is looking for:
            if (SPS_IS_ERR_STATE(ret)) {
Which should be:
            if (SPS30_IS_ERR_STATE(ret)) {
ie the 30 is missing off SPS

**Comment by abrauchli** [comment]
Thanks for reporting this @GKassell, does the PR above fix the issue?

**Comment by rnestler** [comment]
@GKassell This seems fixed by #66 so I'll close this. Feel free to re-open or submit a new issue if you experience any problems.
