### ISSUE TITLE
First measurement read in sps30_example_usage.c always fails

### ISSUE THREAD

**Issue by rwaldura** [Sensirion/embedded-uart-sps#78]
`sps30_example_usage.c` consistently fails to read the very first measurement, in my experience.

`sps30-uart/sps30.h` says:
> sps30_start_measurement() - start measuring
> Once the measurement is started, measurements are retrievable **once per second**
> with sps30_read_measurement.
 
But `sps30_example_usage.c` calls `sps30_start_measurement()` right after `sps30_start_measurement()` -- the first time, without waiting one second before the call. 

I propose moving the sleep call at
https://github.com/Sensirion/embedded-uart-sps/blob/master/sps30-uart/sps30_example_usage.c#L121
to line 95 instead, at the start of the loop.

With this change, all my measurements are consistently successful.

**Comment by MBjoern** [comment]
Good to know, thank you for your inputs
