### ISSUE TITLE
STM32 UART EXAMPLE SPS30

### ISSUE THREAD

**Issue by Pjonkers1975** [Sensirion/embedded-uart-sps#83]
Is there an example of how to port this sensor in a stm32 processor.

**Comment by Pjonkers1975** [comment]
* Copyright (c) 2018, Sensirion AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of Sensirion AG nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#include "sensirion_arch_config.h"
#include "sensirion_uart.h"
#include "main.h"
#include "stm32g4xx_hal.h"

extern UART_HandleTypeDef hlpuart1;

/*
 * INSTRUCTIONS
 * ============
 *
 * Implement all functions where they are marked with TODO: implement
 * Follow the function specification in the comments.
 */

/**
 * sensirion_uart_select_port() - select the UART port index to use
 *                                THE IMPLEMENTATION IS OPTIONAL ON SINGLE-PORT
 *                                SETUPS (only one SPS30)
 *
 * Return:      0 on success, an error code otherwise
 */
int16_t sensirion_uart_select_port(uint8_t port) {
   // return (&hlpuart1);
 return 0;
}

/**
 * sensirion_uart_open() - initialize UART
 *
 * Return:      0 on success, an error code otherwise
 */
int16_t sensirion_uart_open() {

    return (HAL_UARTEx_DisableStopMode(&hlpuart1));
  //  return 0;
}

/**
 * sensirion_uart_close() - release UART resources
 *
 * Return:      0 on success, an error code otherwise
 */
int16_t sensirion_uart_close() {
    // TODO: implement
    return (HAL_UARTEx_EnableStopMode(&hlpuart1));
}

/**
 * sensirion_uart_tx() - transmit data over UART
 *
 * @data_len:   number of bytes to send
 * @data:       data to send
 * Return:      Number of bytes sent or a negative error code
 */
int16_t sensirion_uart_tx(uint16_t data_len, const uint8_t* data) {
    // TODO: implement

    return (HAL_UART_Transmit (&hlpuart1, data, data_len,1000));

}

/**
 * sensirion_uart_rx() - receive data over UART
 *
 * @data_len:   max number of bytes to receive
 * @data:       Memory where received data is stored
 * Return:      Number of bytes received or a negative error code
 */
int16_t sensirion_uart_rx(uint16_t max_data_len, uint8_t* data) {
    // TODO: implement
    return (HAL_UART_Receive (&hlpuart1, data, max_data_len, HAL_MAX_DELAY));
}

/**
 * Sleep for a given number of microseconds. The function should delay the
 * execution for at least the given time, but may also sleep longer.
 *
 * Despite the unit, a <10 millisecond precision is sufficient.
 *
 * @param useconds the sleep time in microseconds
 */
void sensirion_sleep_usec(uint32_t useconds) {
    // TODO: implement
   HAL_Delay(100);


}

**Comment by psachs** [comment]
Hi,

Currently we don't have an official STM32 example with UART support. We are planning to support more platforms and sample implementations in the future.

To port this driver to STM you have to implement the UART communication (as you posted here), but also configure the STM framework to work. You can have a look at the SHT4x I2C example for an STM32F1 (Nucleo) as a reference.

https://github.com/Sensirion/nucleo-i2c-sht4x

Please let us know if you were successful in integrating the sensor or if you need any further help

**Comment by Anzal3c3** [comment]
> * Copyright (c) 2018, Sensirion AG
> * All rights reserved.
> * Redistribution and use in source and binary forms, with or without
> * modification, are permitted provided that the following conditions are met:
> * * Redistributions of source code must retain the above copyright notice, this
> * list of conditions and the following disclaimer.
> * * Redistributions in binary form must reproduce the above copyright notice,
> * this list of conditions and the following disclaimer in the documentation
> * and/or other materials provided with the distribution.
> * * Neither the name of Sensirion AG nor the names of its
> * contributors may be used to endorse or promote products derived from
> * this software without specific prior written permission.
> * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
> * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
> * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
> * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
> * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
> * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
> * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
> * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
> * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
> * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
> * POSSIBILITY OF SUCH DAMAGE.
>   */
> 
> #include "sensirion_arch_config.h" #include "sensirion_uart.h" #include "main.h" #include "stm32g4xx_hal.h"
> 
> extern UART_HandleTypeDef hlpuart1;
> 
> /*
> 
> * INSTRUCTIONS
> * ============
> * Implement all functions where they are marked with TODO: implement
> * Follow the function specification in the comments.
>   */
> 
> /**
> 
> * sensirion_uart_select_port() - select the UART port index to use
> * ```
>                              THE IMPLEMENTATION IS OPTIONAL ON SINGLE-PORT
>   ```
> * ```
>                              SETUPS (only one SPS30)
>   ```
> * Return:      0 on success, an error code otherwise
>   */
>   int16_t sensirion_uart_select_port(uint8_t port) {
>   // return (&hlpuart1);
>   return 0;
>   }
> 
> /**
> 
> * sensirion_uart_open() - initialize UART
> * Return:      0 on success, an error code otherwise
>   */
>   int16_t sensirion_uart_open() {
>   return (HAL_UARTEx_DisableStopMode(&hlpuart1));
>   //  return 0;
>   }
> 
> /**
> 
> * sensirion_uart_close() - release UART resources
> * Return:      0 on success, an error code otherwise
>   */
>   int16_t sensirion_uart_close() {
>   // TODO: implement
>   return (HAL_UARTEx_EnableStopMode(&hlpuart1));
>   }
> 
> /**
> 
> * sensirion_uart_tx() - transmit data over UART
> * @data_len:   number of bytes to send
> * @DaTa:       data to send
> * Return:      Number of bytes sent or a negative error code
>   _/
>   int16_t sensirion_uart_tx(uint16_t data_len, const uint8_t_ data) {
>   // TODO: implement
>   return (HAL_UART_Transmit (&hlpuart1, data, data_len,1000));
> 
> }
> 
> /**
> 
> * sensirion_uart_rx() - receive data over UART
> * @data_len:   max number of bytes to receive
> * @DaTa:       Memory where received data is stored
> * Return:      Number of bytes received or a negative error code
>   _/
>   int16_t sensirion_uart_rx(uint16_t max_data_len, uint8_t_ data) {
>   // TODO: implement
>   return (HAL_UART_Receive (&hlpuart1, data, max_data_len, HAL_MAX_DELAY));
>   }
> 
> /**
> 
> * Sleep for a given number of microseconds. The function should delay the
> * execution for at least the given time, but may also sleep longer.
> * Despite the unit, a <10 millisecond precision is sufficient.
> * @param useconds the sleep time in microseconds
>   */
>   void sensirion_sleep_usec(uint32_t useconds) {
>   // TODO: implement
>   HAL_Delay(100);
> 
> }

this code does not even transmit the command it ends up being error.
